Grade 8/Unit0/Unit0/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path("", include("homepage.urls")),
    path("movies/", include("movies.urls")),
    path("search/", include("search.urls")),
    path("genres/", include("genres.urls")),
    path("accounts/", include("accounts.urls")),
]

Grade 8/Unit0/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

Grade 8/Unit0/genres/urls.py
from django.urls import path
from . import views

app_name = 'genres'
urlpatterns = [
    path('action/', views.action, name='action'),
    path('comedy/', views.comedy, name='comedy'),
    path('horror/', views.horror, name='horror'),
    path('fantasy/', views.fantasy, name='fantasy'),
]

Grade 8/Unit0/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
	path("", views.index, name="index"),
]

Grade 8/Unit0/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:movie_name>/', views.detail, name='detail'),
    path('like/<str:movie_name>/', views.like, name='like'),
	path('dislike/<str:movie_name>/', views.dislike, name='dislike'),
] 

Grade 8/Unit0/search/urls.py
from django.urls import path
from . import views

app_name = 'search'
urlpatterns = [
    path('', views.search, name='search'),
]

Grade 8/Unit0/homepage/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
	title = models.CharField(max_length=200)
	year = models.IntegerField()
	genre = models.CharField(max_length=200)
	director = models.CharField(max_length=200)
	stars = models.CharField(max_length=200, default="")
	rating = models.DecimalField(max_digits=3, decimal_places=1)
	image = models.CharField(max_length=1000)
	description = models.TextField()
	linkName = models.CharField(max_length=200, default="")

	def __str__(self):
		return self.title

Grade 8/Unit0/homepage/views.py
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from . import models

# Create your views here.
# All views need to be authenticated

def index(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse("accounts:login"))
		
	# Checking for movies in user session
	if 'likedMovies' not in request.session:
		request.session['likedMovies'] = []
		request.session['dislikedMovies'] = []
		request.session['genreWeightedScore'] = {}
		return render(request, 'homepage/index.html', {
			# Setting recommended movies to false for django templating
			'recommendedMovies': False,
		})

	# Check if user list is empty
	if len(request.session['likedMovies']) == 0:
		return render(request, 'homepage/index.html', {
			# Setting recommended movies to false for django templating
			'recommendedMovies': False,
		})

	# Create list of liked genres
	likedGenres = []
	for key, value in request.session['genreWeightedScore'].items():
		if value > 0:
			likedGenres.append(key)

	# # Get movies from database where title not in dislikedMovies and not in likedMovies
	# # and genre in likedGenres, and rating is greater than 5
	# # order in descending order, and limit by 10
	# movies = models.Movie.objects.filter(
	# 	~Q(title__in=request.session['likedMovies']),
	# 	~Q(title__in=request.session['dislikedMovies']),
	# 	genre__in=likedGenres, rating__gte=5
	# ).order_by('-rating').distinct()[:6]

	# Get all movies then perform filter
	movies = models.Movie.objects.all()

	# Get rid of movies that are in likedMovies and dislikedMovies
	for movie in movies:
		if movie.title in request.session['likedMovies']:
			movies = movies.exclude(title=movie.title)
		if movie.title in request.session['dislikedMovies']:
			movies = movies.exclude(title=movie.title)

	# Get rid of movies that are not in likedGenres
	for movie in movies:
		if movie.genre not in likedGenres:
			movies = movies.exclude(title=movie.title)

	# Get rid of movies that are not greater than 5
	for movie in movies:
		if movie.rating < 5:
			movies = movies.exclude(title=movie.title)

	# get movies from movies where titles are similar to titles in likedMovies
	recommendedMovies = []

	# Make sure likedMovies has no duplicates
	likedMovies = list(set(request.session['likedMovies']))
	print(f'DEBUG INFO (SESSION) >> {request.session["likedMovies"]}')

	for movie in movies:
		for likedMovie in request.session['likedMovies']:
			# split likedMovie into array of words
			likedMovie = likedMovie.split()

			# exclude common words and articles from likedMovie title
			for word in likedMovie:
				if word.lower() in ['the', 'a', 'an', 'and', 'or', 'but', 'for', 'of', 'nor', 'on', 'to', 'with']:
					likedMovie.remove(word)

			# remove the word "the" from the movie title
			# need this bcos previous thing isn't working on the word "the"
			if 'the' in likedMovie:
				likedMovie.remove('the')
			elif 'The' in likedMovie:
				likedMovie.remove('The')

			# Remove punctuation from likedMovie title
			for word in likedMovie:
				if not word.isalpha():
					likedMovie.remove(word)


			print(f'DEBUG INFO (LIKED MOVIE) >> {likedMovie}')

			# get movies with similar titles
			for word in likedMovie:
				if word in movie.title:
					recommendedMovies.append(movie)
					break
	# Remove any duplicates from recommendedMovies
	recommendedMovies = list(dict.fromkeys(recommendedMovies))

	# Get list of genre values if the value is more than 1
	genres = []
	for key, value in request.session['genreWeightedScore'].items():
		if value > 1:
			genres.append(value)

	if len(genres) > 1:
		same = allsame(genres)

		if not same:
			# Sort ordered movies by genre
			# The greater the value a genre has in session["genres"], the higher up the movies should be in the list
			recommendedMovies = sorted(
				recommendedMovies, key=lambda x: request.session['genreWeightedScore'][x.genre], reverse=True)
		else:
			# Sort ordered movies by rating
			recommendedMovies = sorted(
				recommendedMovies, key=lambda x: x.rating, reverse=True)

	else:
		recommendedMovies = sorted(
				recommendedMovies, key=lambda x: request.session['genreWeightedScore'][x.genre], reverse=True)

	# Shortening recommended movies and re-sorting by rating
	if len(recommendedMovies) < 6:
		movies = sorted(
				movies, key=lambda x: x.rating, reverse=True)
		
		recommendedMovies = concatenate(recommendedMovies, movies)

	recommendedMovies = recommendedMovies[:6]
	recommendedMovies = sorted(
			recommendedMovies, key=lambda x: x.rating, reverse=True)

	# get liked movie objects and store in list
	likedMovies = []
	try:
		for movie in request.session['likedMovies']:
			likedMovies.append(models.Movie.objects.get(title=movie))
	except models.Movie.DoesNotExist:
		likedMovies = None

	# get disliked movie objects and store in list
	dislikedMovies = []
	try:
		for movie in request.session['dislikedMovies']:
			dislikedMovies.append(models.Movie.objects.get(title=movie))
	except models.Movie.DoesNotExist:
		dislikedMovies = None

	# Some debugging stuff
	print(request.session['likedMovies'])
	print(recommendedMovies)

	return render(request, 'homepage/index.html', {
		'recommendedMovies': recommendedMovies,
		'likedMovies': likedMovies,
		'dislikedMovies': dislikedMovies,
	})


# Helper function to see if all items in list are the same value
def allsame(array):
	same = True

	# Comparing each element with first item
	for element in array:
		if element != array[0]:
			same = False
			break

	return True if same else False

def concatenate(arr1, arr2):
	for element in arr2:
		arr1.append(element)

	return arr1

Grade 8/Unit0/homepage/templates/homepage/index.html
{% extends "./layout.html" %}
{% load static %}

{% block head %}
<title>Home</title>
<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/icon type">
{% endblock %}

{% block body %}
<h1 style="text-align:center;"> Homepage </h1>
{% if recommendedMovies %}
<h2 style="text-align:center;"> Recommended Movies </h2>
<div class="row">
	{% for movie in recommendedMovies %}
	<div class="card mb-3 bg-dark" style="max-width: 540px;">
		<div class="row g-0">
			<div class="col-md-4">
				<img src="{{movie.image}}" class="img-fluid rounded-start" alt="...">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title">{{movie.title}}</h5>
					<p class="card-text">{{ movie.description }}</p>
					<a href="{% url 'movies:detail' movie.linkName %}" class="btn btn-primary">Learn More</a>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
<br>
<h2 style="text-align:center;"> Liked Movies </h2>
<div class="row">
	{% for movie in likedMovies %}
	<div class="card mb-3 bg-dark" style="max-width: 540px;">
		<div class="row g-0">
			<div class="col-md-4">
				<img src="{{movie.image}}" class="img-fluid rounded-start" alt="...">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title">{{movie.title}}</h5>
					<p class="card-text">{{ movie.description }}</p>
					<a href="{% url 'movies:detail' movie.linkName %}" class="btn btn-primary">Learn More</a>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
<br>
<h2 style="text-align:center;"> Disliked Movies </h2>
<div class="row">
	{% for movie in dislikedMovies %}
	<div class="card mb-3 bg-dark" style="max-width: 540px;">
		<div class="row g-0">
			<div class="col-md-4">
				<img src="{{movie.image}}" class="img-fluid rounded-start" alt="...">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title">{{movie.title}}</h5>
					<p class="card-text">{{ movie.description }}</p>
					<a href="{% url 'movies:detail' movie.linkName %}" class="btn btn-primary">Learn More</a>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</div>

{% else %}
<h3 style="text-align:center; padding-top: 2%;"> You haven't voted on any movies! </h2>
	<p style="color: #686868; text-align: center;">Without info on what movies you like, we can't accurately suggest new
		ones to you!</p>
	{% endif %}
	{% endblock %}

Grade 8/Unit0/homepage/templates/homepage/layout.html
{% load static %}
<!DOCTYPE html>

<html style="overflow-y: scroll">
	<head>
		<!-- Bootstrap Framework Imports -->
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
			integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
			crossorigin="anonymous"
		/>
		<script
			src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
			integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
			integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
			crossorigin="anonymous"
		></script>
		<script
			src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
			integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
			crossorigin="anonymous"
		></script>

		<!-- Custom Imports -->
		<link rel="stylesheet" href="{% static 'styles.css' %}" />
		{% block head %} {% endblock %}
	</head>
	<body style="position: absolute">
		<nav class="navbar sticky-top navbar-dark bg-custom navbar-expand-lg">
			<a class="navbar-brand" href="#">Bootleg IMDB</a>
			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url 'movies:index' %}">Movies</a>
					</li>

					<li class="nav-item dropdown">
						<a
							class="nav-link dropdown-toggle"
							href="#"
							id="navbarDropdown"
							role="button"
							data-toggle="dropdown"
							aria-haspopup="true"
							aria-expanded="false"
						>
							Genres
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'genres:action' %}">Action</a>
							<a class="dropdown-item" href="{% url 'genres:comedy' %}">Comedy</a>
							<a class="dropdown-item" href="{% url 'genres:horror' %}">Horror</a>
							<a class="dropdown-item" href="{% url 'genres:fantasy' %}">Fantasy</a>
							<div class="dropdown-divider"></div>
						</div>
					</li>
				</ul>
				<form class="form-inline my-2 my-lg-0" action="{% url 'search:search' %}" method="POST">
					{% csrf_token %}
					<input
						class="form-control mr-sm-2"
						name="moviename"
						id="moviename"
						type="search"
						placeholder="Search"
						aria-label="Search"
					/>
					<button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</nav>

		<div name="main-page" class="padding-alignments" style="padding-top: 0.5%">{% block body %} {% endblock %}</div>
	</body>
	<footer style="margin-top: 1%">
			<p style="text-align: center; color: rgb(75, 75, 75)">Data provided by the <a href="https://www.imdb.com/" style="color: rgb(100, 100, 100)">Internet Movie database</a> ||| <a href="{% url 'accounts:logout' %}" style="color: rgb(100, 100, 100)">Logout</a></p>
	</footer>
</html>